// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ф.Models;

#nullable disable

namespace ф.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231104104401_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ф.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sweets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fruits"
                        });
                });

            modelBuilder.Entity("ф.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Coca-Cola",
                            Price = 1.1m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Pepsi",
                            Price = 1.3m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Fanta",
                            Price = 1.4m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Snickers",
                            Price = 1.6m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Mars",
                            Price = 1.7m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Twix",
                            Price = 1.8m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Apple",
                            Price = 2m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Banana",
                            Price = 2.1m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Peach",
                            Price = 2.3m
                        });
                });

            modelBuilder.Entity("ф.Models.Product", b =>
                {
                    b.HasOne("ф.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ф.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
