// <auto-generated />
using System;
using Lesson07;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson07.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231105104742_Use_TPT")]
    partial class Use_TPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lesson07.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Lesson07.Models.Employee", b =>
                {
                    b.HasBaseType("Lesson07.Models.Person");

                    b.Property<DateTime>("Hiredate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("Lesson07.Models.Student", b =>
                {
                    b.HasBaseType("Lesson07.Models.Person");

                    b.Property<decimal>("AverageGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("Lesson07.Models.Teacher", b =>
                {
                    b.HasBaseType("Lesson07.Models.Person");

                    b.Property<double>("Experience")
                        .HasColumnType("float");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Teacher", (string)null);
                });

            modelBuilder.Entity("Lesson07.Models.Security", b =>
                {
                    b.HasBaseType("Lesson07.Models.Employee");

                    b.Property<int>("Smena")
                        .HasColumnType("int");

                    b.ToTable("Security", (string)null);
                });

            modelBuilder.Entity("Lesson07.Models.FullTimeStudent", b =>
                {
                    b.HasBaseType("Lesson07.Models.Student");

                    b.Property<int>("Smena")
                        .HasColumnType("int");

                    b.ToTable("FullTimeStudent", (string)null);
                });

            modelBuilder.Entity("Lesson07.Models.PartTimeStudent", b =>
                {
                    b.HasBaseType("Lesson07.Models.Student");

                    b.Property<int>("StudyDays")
                        .HasColumnType("int");

                    b.ToTable("PartTimeStudent", (string)null);
                });

            modelBuilder.Entity("Lesson07.Models.Employee", b =>
                {
                    b.HasOne("Lesson07.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Lesson07.Models.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lesson07.Models.Student", b =>
                {
                    b.HasOne("Lesson07.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Lesson07.Models.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lesson07.Models.Teacher", b =>
                {
                    b.HasOne("Lesson07.Models.Person", null)
                        .WithOne()
                        .HasForeignKey("Lesson07.Models.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lesson07.Models.Security", b =>
                {
                    b.HasOne("Lesson07.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("Lesson07.Models.Security", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lesson07.Models.FullTimeStudent", b =>
                {
                    b.HasOne("Lesson07.Models.Student", null)
                        .WithOne()
                        .HasForeignKey("Lesson07.Models.FullTimeStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lesson07.Models.PartTimeStudent", b =>
                {
                    b.HasOne("Lesson07.Models.Student", null)
                        .WithOne()
                        .HasForeignKey("Lesson07.Models.PartTimeStudent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
